import ListQuotes from "@components/quotes/ListQuotes";
import { getQuotes } from "utils";

export const metadata = {
  title: "Lapp",
  description: "Generated by create next app",
};


export default async function page() {
  const {
    state,
    sales_org,
    region,
    dsm,
    account_manager,
    vertical_market,
    quotes,
  } = await getQuotes();

  return (
    <ListQuotes
      defaultQuotes={quotes}
      state={state}
      sales_org={sales_org}
      region={region}
      dsm={dsm}
      account_manager={account_manager}
      vertical_market={vertical_market}
    />
  );
}
