export const formFields = [
  {
    id: 0,
    name: "material_id",
    type: "text",
    placeholder: "Enter Material",
    label: "Material",
    disabled: 0,
  },
  {
    id: 1,
    name: "quantity",
    type: "number",
    placeholder: "Enter Quantity",
    label: "Quantity",
    disabled: 0,
  },
  {
    id: 2,
    name: "uom",
    type: "text",
    placeholder: "Enter UOM",
    label: "UOM",
    disabled: 1,
  },
  {
    id: 3,
    name: "stock_6100",
    type: "number",
    placeholder: "Enter Stock in 6100",
    label: "Stock in 6100",
    disabled: 1,
  },
  {
    id: 4,
    name: "stock_6120",
    type: "number",
    placeholder: "Enter Stock in 6120",
    label: "Stock in 6120",
    disabled: 1,
  },
  {
    id: 5,
    name: "stock_6130",
    type: "number",
    placeholder: "Enter Stock in 6130",
    label: "Stock in 6130",
    disabled: 1,
  },
  {
    id: 6,
    name: "stock_6140",
    type: "number",
    placeholder: "Enter Stock in 6140",
    label: "Stock in 6140",
    disabled: 1,
  },

  {
    id: 10,
    name: "low_discount",
    type: "number",
    placeholder: "Enter Low Discount",
    label: "Low Discount %",
    disabled: 1,
  },
  {
    id: 11,
    name: "average_discount",
    type: "number",
    placeholder: "Enter Average Discount",
    label: "Average Discount %",
    disabled: 1,
  },
  {
    id: 12,
    name: "high_discount",
    type: "number",
    placeholder: "Enter High Discount",
    label: "High Discount %",
    disabled: 1,
  },
  {
    id: 13,
    name: "line_notes",
    type: "text",
    placeholder: "Enter Notes",
    label: "Notes",
    disabled: 0,
  },

  {
    id: 9,
    name: "level_5_base_cu",
    type: "number",
    placeholder: "Enter Base Copper Price",
    label: "Base Copper Price $",
    disabled: 1,
  },
  {
    id: 14,
    name: "discounts",
    type: "number",
    placeholder: "Enter Discounts",
    label: "Discount %",
    disabled: 0,
  },
  {
    id: 15,
    name: "copper_base_price",
    type: "number",
    placeholder: "Enter Proposed CU BP w/discount",
    label: "Proposed CU BP w/discount $",
  },
  {
    id: 16,
    name: "full_base_price",
    type: "number",
    placeholder: "Enter Full Copper Price",
    label: "Full Copper Price $",
  },
  {
    id: 17,
    name: "margin_full_copper",
    type: "number",
    placeholder: "Enter Margin at full copper",
    label: "Margin at full copper %",
  },
  {
    id: 18,
    name: "line_value",
    type: "number",
    placeholder: "Enter Line value",
    label: "Line value $",
  },
  {
    id: 19,
    name: "line_cogs",
    type: "number",
    placeholder: "Enter Line COGS",
    label: "Line COGS $",
  },
  {
    id: 7,
    name: "description",
    type: "text",
    placeholder: "Enter Material Description",
    label: "Material Description",
    disabled: 1,
  },

  {
    id: 8,
    name: "product_family",
    type: "text",
    placeholder: "Enter Product Family",
    label: "Product Family",
    disabled: 1,
  },
];
